version: '3.4'

services:   
  
  cart:
    build:
      context: ../../
      dockerfile: /host/InstaRent.Cart.HttpApi.Host/Dockerfile
    depends_on:
      - redis 

networks:
  instarent-network:
    external: true