version: '3.4'

services:
  redis:
    container_name: redis
    image: redis:alpine
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
    networks: 
      - instarent-network
      
  
  cart:
    build:
      context: ../../
      dockerfile: /host/InstaRent.Cart.HttpApi.Host/Dockerfile
    depends_on:
      - redis 

networks:
  instarent-network:
    external: true